### ISSUE TITLE
Using it in a production app

### ISSUE THREAD

**Issue by Raathigesh** [amsb/mobx-reactor#1]
We are starting developement of a React app and really like the simplistic approach of Mobx. But after working with Redux we also like to have uni-directional data flow in the app. Mobx-reactor is doing just that but unfortunately it's still experimental. 

Since we are about to start the development of our app, what is your recommendation? Should we start using mobx-reactor as is? What is the timeline of having reactor production ready?

Or we would be just fine without actions and uni-directional data flow?

**Comment by amsb** [comment]
Thank you for your interest! This project is still experimental as I continue to evolve it be a complimentary part of the MobX ecosystem. Currently, I'm watching the development of [MobX 2.2](https://github.com/mobxjs/mobx/issues/219) which will include its own `@action` decorator. In fact, this project may well be superseded by additions to the core MobX libraries and a simple example of how to implement flux-like state management. For example, consider [this example](https://github.com/mobxjs/mobx-react-boilerplate/issues/8).
